### ISSUE TITLE
Did you get it from somewhere?

### ISSUE THREAD

**Issue by edysegura** [allanthomasof/SalaryPaycheckCalculator#2]
Hi @allanthomasof!

I didn't teach [this way](https://github.com/allanthomasof/SalaryPaycheckCalculator/blob/master/client/js/script.js) to programming in JavaScript. Where have you learn that?

**Comment by allanthomasof** [comment]
Hi @edysegura 

I learned researching during the development of the first part of the homework. It was a solution that worked well, so I decided to use it again.

**Comment by edysegura** [comment]
I recommend you to use a [module](http://addyosmani.com/resources/essentialjsdesignpatterns/book/#modulepatternjavascript) or [object oriented](http://rmurphey.com/blog/2009/10/15/using-objects-to-organize-your-code/) approach to create more reliable and sustainable applications.

Cheers!
